const albumDataActionTypes = {
	ALBUM_DATA_REQUESTED: 'ALBUM_DATA_REQUESTED',

	ALBUM_DATA_STARTED: 'ALBUM_DATA_STARTED',
	ALBUM_DATA_SUCCESS: 'ALBUM_DATA_SUCCESS',
	ALBUM_DATA_FAILURE: 'ALBUM_DATA_FAILURE',
};

export default albumDataActionTypes;
