export const ALBUM_DATA_REQUESTED = 'ALBUM_DATA_REQUESTED';
export const ALBUMDATA_DATA_LOADED = 'ALBUMDATA_DATA_LOADED';
export const RESUME_DATA_REQUESTED = 'RESUME_DATA_REQUESTED';
export const RESUME_DATA_LOADED = 'RESUME_DATA_LOADED';
export const API_ERRORED = 'API_ERRORED';
