const albumMetaDataActionTypes = {
	ALBUM_META_DATA_REQUESTED: 'ALBUM_META_DATA_REQUESTED',

	ALBUM_META_DATA_STARTED: 'ALBUM_META_DATA_STARTED',
	ALBUM_META_DATA_SUCCESS: 'ALBUM_META_DATA_SUCCESS',
	ALBUM_META_DATA_FAILURE: 'ALBUM_META_DATA_FAILURE',

};

export default albumMetaDataActionTypes;
