/* eslint-disable import/prefer-default-export */
export const userActionTypes = {
	CHANGE_TO_USER_ROLE_START: 'CHANGE_TO_USER_ROLE_START',
	CHANGE_TO_USER_ROLE_SUCCESS: 'CHANGE_TO_USER_ROLE_SUCCESS',
	CHANGE_TO_USER_ROLE_FAILURE: 'CHANGE_TO_USER_ROLE_FAILURE',

	CHANGE_DISPLAY_NAME_START: 'CHANGE_DISPLAY_NAME_START',
	CHANGE_DISPLAY_NAME_SUCCESS: 'CHANGE_DISPLAY_NAME_SUCCESS',
	CHANGE_DISPLAY_NAME_FAILURE: 'CHANGE_DISPLAY_NAME_FAILURE',

	SET_CURRENT_USER: 'SET_CURRENT_USER',
	LISTEN_CURRENT_USER: 'LISTEN_CURRENT_USER',
	UPDATE_LOCAL_USER: 'UPDATE_LOCAL_USER',

	CHANGE_REQUEST_ADMIN_ROLE_START: 'CHANGE_REQUEST_ADMIN_ROLE_START',
	CHANGE_REQUEST_ADMIN_ROLE_SUCCESS: 'CHANGE_REQUEST_ADMIN_ROLE_SUCCESS',
	CHANGE_REQUEST_ADMIN_ROLE_FAILURE: 'CHANGE_REQUEST_ADMIN_ROLE_FAILURE',

};
